name: build-api

on:
  push:
    branches:
      - "main"
    paths:
      - 'DockerCourseApi/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Spin up database
        run: docker compose up -d database
      -
        name: Seed database
        run: |
          chmod +x ./Database/wait-and-run.sh
          docker compose run --build database-seed
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/api:${{github.run_number}} \
            -f ./DockerCourseApi/DockerCourseApi/Dockerfile \
            --network host \
            ./DockerCourseApi/.
      -
        name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:${{github.run_number}}

        # name: Build and push
        # uses: docker/build-push-action@v4
        # with:
        #   context: ./DockerCourseApi/.
        #   file: ./DockerCourseApi/DockerCourseApi/Dockerfile
        #   network: host
        #   push: true
        #   tags: |
        #     ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
        #     ${{ secrets.DOCKERHUB_USERNAME }}/api:${{github.run_number}}
      -
        name: Tear down database
        if: always()
        run: docker compose down database
